name: Continuous Delivery

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-release-robustServer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew (robustServer)
        working-directory: robustServer
        run: chmod +x ./gradlew

      - name: Build robustServer
        working-directory: robustServer
        run: ./gradlew build

      - name: Get commit message
        id: get_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create GitHub Release (robustServer)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: robustServer-${{ github.sha }}-server
          release_name: robustServer Release ${{ github.sha }}
          body: ${{ env.COMMIT_MSG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (robustServer)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: robustServer-${{ github.sha }}-server
          files: robustServer/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release-robustClient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew (robustClient)
        working-directory: robustClient
        run: chmod +x ./gradlew

      - name: Build robustClient
        working-directory: robustClient
        run: ./gradlew build

      - name: Get commit message
        id: get_commit_client
        run: echo "COMMIT_MSG_CLIENT=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Create GitHub Release (robustClient)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: robustClient-${{ github.sha }}-client
          release_name: robustClient Release ${{ github.sha }}
          body: ${{ env.COMMIT_MSG_CLIENT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset (robustClient)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: robustClient-${{ github.sha }}-client
          files: robustClient/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
