name: Continuous Integration

on:
  push:
    branches: [main, tests]
    paths:
      - 'robustClient/**'
      - 'robustServer/**'
      - '.github/workflows/**'
  pull_request:
    branches: [main, tests]
    paths:
      - 'robustClient/**'
      - 'robustServer/**'
      - '.github/workflows/**'

jobs:
  test-robustClient:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew (robustClient)
        working-directory: robustClient
        run: chmod +x ./gradlew

      - name: Run tests (robustClient)
        working-directory: robustClient
        run: ./gradlew test

      - name: Generate coverage report (robustClient)
        working-directory: robustClient
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report (robustClient)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-robustClient
          path: robustClient/build/reports/jacoco/test/html

  test-robustServer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew (robustServer)
        working-directory: robustServer
        run: chmod +x ./gradlew

      - name: Run tests (robustServer)
        working-directory: robustServer
        run: ./gradlew test

      - name: Generate coverage report (robustServer)
        working-directory: robustServer
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report (robustServer)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-robustServer
          path: robustServer/build/reports/jacoco/test/html
