name: Debug Comment Check

on:
  push:
    branches: [main, tests]
  pull_request:
    branches: [main, tests]

jobs:
  check-debug-comments:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for // DEBUG comments
        run: |
          set -o pipefail
          if grep -rn \
            --exclude-dir=.git \
            --exclude-dir=build \
            --exclude='*.md' \
            --exclude='.github/workflows/comment-check.yml' \
            '// DEBUG' . | tee /dev/stderr; then
            echo "ERROR: Found // DEBUG comment(s). Please remove before committing."
            exit 1
          else
            echo "No // DEBUG comments found."
          fi

      - name: Check for /* DEBUG ... */ comments
        run: |
          set -o pipefail
          if grep -rn \
            --exclude-dir=.git \
            --exclude-dir=build \
            --exclude='*.md' \
            --exclude='.github/workflows/comment-check.yml' \
            '/\* DEBUG' . | tee /dev/stderr; then
            echo "ERROR: Found /* DEBUG ... */ comment(s). Please remove before committing."
            exit 1
          else
            echo "No /* DEBUG ... */ comments found."
          fi
